Include start / end in exceptions thrown by type inspector
aaubry/YamlDotNet pull request #624
Opened 2021-07-15 18:24 UTC by jairbubbles

- Add two new exceptions `PropertyNotFoundException` and  `MultiplePropertiesFoundException` than inherits from `YamlException`
- Adapt the code to pass the current property as a `Scalar` which includes `Start` / `End`

2021-07-15 22:04 UTC, aaubry requested changes
I think including the location of the error is a useful improvement, however I don't think that changing `ITypeInspector` to take a scalar is a good idea for the following reasons:
- That interface should not be coupled to YAML structure. It is an abstraction over the .NET type system. In principle it could be used in contexts that have nothing to do with YAML.
- This is a breaking change that will force anyone who implements that interface to change their code. `ITypeInspector` is a frequently used extension point, so the impact would be high.

Instead I would suggest to catch the exception(s) and wrap them. In principle, this would also be a breaking change, although I believe that the impact would be quite low as I don't expect code to rely on these exceptions specifically.

What do you think?

2021-07-16 03:33 UTC, jairbubbles commented
@aaubry As it was not massively used in the solution I thought that maybe it was an internal interface.I tried my luck!  ☺

By the way there is this nice analyzer to detect breaking changes in the public API: 
https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md

Please note that I'm currently using `YamlDotNet` to create a linter for a .yml file and appart from the issue fixed here, it would have been nice to receive multiple serialization exceptions. For example you have a missing property at the beginning of the file and a syntax error at the end. 

We could accumulate the serialization errors and wrap them in a new exception type like `MultipleYamlException`.  What do you think @aaubry?

2021-08-04 10:22 UTC, jairbubbles commented
Hi @aaubry, I changed the code accordingly to your remarks, what do you think about it?

2021-08-06 08:44 UTC, aaubry commented
Thanks and sorry for the delay!

2021-08-06 08:44 UTC, merged

2021-08-06 10:24 UTC, jairbubbles commented
Thx! Let me know when you release a version with the fix.

2021-08-19 08:19 UTC, jairbubbles commented
Hi @aaubry  any plans to release a version including this fix?

2022-07-23 17:45 UTC, aaubry commented
This feature has been released in [version 12.0.0](https://github.com/aaubry/YamlDotNet/releases/tag/v12.0.0).